# Generated by Django 4.0.2 on 2022-05-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='seatingplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room', models.CharField(max_length=130)),
                ('Total', models.IntegerField()),
                ('Date', models.CharField(max_length=130)),
                ('Shift', models.CharField(max_length=130)),
            ],
        ),
    ]
